package cn.govproc.supplychain.content;
import cn.govproc.supplychain.common.PageSupport;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.util.Map;
import org.springframework.http.HttpStatus;import org.springframework.jdbc.core.simple.JdbcClient;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/admin/content/footer-links")
public class FooterLinkAdminController {private final JdbcClient jdbc;public FooterLinkAdminController(JdbcClient jdbc){this.jdbc=jdbc;}
 @GetMapping Object list(@RequestParam String group,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="10")int pageSize,@RequestParam(defaultValue="")String keyword,@RequestParam(required=false)Integer status){return PageSupport.query(jdbc,"SELECT id,link_group AS linkGroup,title,link_url AS linkUrl,open_target AS openTarget,sort_order AS sortOrder,status FROM portal_footer_link WHERE deleted_at IS NULL AND link_group=:group","q.sortOrder,q.id",Map.of("group",group),page,pageSize,keyword,status,java.util.List.of("title","linkUrl"),"status");}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) @Transactional void create(@Valid @RequestBody Request r){jdbc.sql("INSERT INTO portal_footer_link(link_group,title,link_url,open_target,sort_order,status) VALUES(:linkGroup,:title,:linkUrl,:openTarget,:sortOrder,:status)").paramSource(r).update();}
 @PutMapping("/{id}") @Transactional void update(@PathVariable long id,@Valid @RequestBody Request r){int changed=jdbc.sql("UPDATE portal_footer_link SET link_group=:linkGroup,title=:title,link_url=:linkUrl,open_target=:openTarget,sort_order=:sortOrder,status=:status WHERE id=:id AND deleted_at IS NULL").params(Map.of("id",id,"linkGroup",r.linkGroup(),"title",r.title(),"linkUrl",r.linkUrl(),"openTarget",r.openTarget(),"sortOrder",r.sortOrder(),"status",r.status())).update();if(changed==0)throw new IllegalArgumentException("页脚链接不存在");}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) void delete(@PathVariable long id){jdbc.sql("UPDATE portal_footer_link SET deleted_at=NOW(),status=0 WHERE id=:id").param("id",id).update();}
 public record Request(@Pattern(regexp="OFFICIAL|SERVICE")String linkGroup,@NotBlank String title,@NotBlank String linkUrl,@Pattern(regexp="SELF|BLANK")String openTarget,@NotNull Integer sortOrder,@NotNull Integer status){}
}
