import React,{useEffect,useState} from "react";
import {api,Row} from "./main";
type Detail={task:Row;items:Row[]};
const money=(value:any)=>`¥${Number(value||0).toFixed(2)}`;
export function PurchaseWorkbench({go,reloadCart}:{go:(view:string)=>void;reloadCart:()=>Promise<void>}){
 const[tasks,setTasks]=useState<Row[]>([]),[detail,setDetail]=useState<Detail|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=async()=>setTasks(await api<Row[]>("/api/client/purchase-tools/imports"));useEffect(()=>{void load();},[]);
 const upload=async(file?:File)=>{if(!file)return;setBusy(true);setError("");try{const data=new FormData();data.append("file",file);const response=await fetch("/api/client/purchase-tools/imports",{method:"POST",body:data});const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||"导入失败");setDetail(body);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const open=async(id:number)=>setDetail(await api<Detail>(`/api/client/purchase-tools/imports/${id}`));
 const changeQuantity=async(row:Row,quantity:number)=>{if(!detail)return;setBusy(true);try{setDetail(await api<Detail>(`/api/client/purchase-tools/imports/${detail.task.id}/items/${row.id}`,{method:"PUT",body:JSON.stringify({quantity})}));await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const remove=async(row:Row)=>{if(!detail)return;setBusy(true);try{setDetail(await api<Detail>(`/api/client/purchase-tools/imports/${detail.task.id}/items/${row.id}`,{method:"DELETE"}));await load();}finally{setBusy(false);}};
 const add=async()=>{if(!detail)return;setBusy(true);try{await api(`/api/client/purchase-tools/imports/${detail.task.id}/add-to-cart`,{method:"POST"});await reloadCart();go("cart");}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <main className="page purchase-workbench"><header><div><span>PROCUREMENT TOOLS</span><h1>批量采购工作台</h1><p>通过 Excel 一次导入多个 SKU，系统会逐行检查商品状态、数量和库存。</p></div><a href="/api/client/purchase-tools/imports/template">下载导入模板</a></header>
 <section className="purchase-upload"><label><b>{busy?"正在处理…":"上传 Excel 文件"}</b><small>仅支持系统模板和 .xlsx 文件，单次数量为 1–9999。</small><input disabled={busy} type="file" accept=".xlsx" onChange={e=>void upload(e.target.files?.[0])}/></label>{error&&<p>{error}</p>}</section>
 {detail&&<section className="purchase-preview"><header><div><h2>导入预览</h2><p>{detail.task.fileName} · 共 {detail.task.totalRows} 行，有效 {detail.task.validRows} 行，异常 {detail.task.invalidRows} 行</p></div><nav>{Number(detail.task.invalidRows)>0&&<a href={`/api/client/purchase-tools/imports/${detail.task.id}/errors.xlsx`}>下载错误明细</a>}<a href={`/api/client/purchase-tools/imports/${detail.task.id}/quotation.xlsx`}>导出报价单</a><button disabled={busy||!Number(detail.task.validRows)} onClick={()=>void add()}>有效商品加入购物车</button></nav></header><div className="purchase-grid purchase-grid-head"><span>行号</span><span>商品信息</span><span>价格对比</span><span>数量 / 库存</span><span>校验结果 / 操作</span></div>{detail.items.map(row=><article className="purchase-grid" key={row.id}><span>{row.rowNumber}</span><div className="purchase-product">{row.image&&<img src={row.image}/>}<span><b>{row.title||row.skuCode||"未识别商品"}</b><small>SKU：{row.skuCode||"—"}</small></span></div><span>{row.status==="VALID"||row.skuId?<><b>采购价 {money(row.salePrice)}</b><small>会员价 {money(row.memberPrice)} · 市场价 {money(row.marketPrice)}</small></>:"—"}</span><span>{row.skuId?<label className="purchase-quantity"><input type="number" min="1" max="9999" defaultValue={row.quantity} disabled={busy} onBlur={e=>{const value=Number(e.target.value);if(value!==Number(row.quantity)&&value>0)void changeQuantity(row,value);}}/> 件</label>:<>{row.quantity||"—"} 件</>}<small>{row.availableStock!=null?`可售库存 ${row.availableStock}`:""}</small></span><span><i className={row.status==="VALID"?"valid":"invalid"}>{row.status==="VALID"?"校验通过":row.errorMessage}</i><button className="purchase-remove" disabled={busy} onClick={()=>void remove(row)}>移除</button></span></article>)}</section>}
 <section className="purchase-history"><h2>最近导入</h2>{tasks.length?tasks.map(row=><button key={row.id} onClick={()=>void open(row.id)}><span><b>{row.fileName}</b><small>{row.createdAt}</small></span><em>有效 {row.validRows} / 异常 {row.invalidRows}</em><i>查看 ›</i></button>):<p>暂无导入记录</p>}</section></main>;
}
