CREATE TABLE home_ad_group (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  layout_type VARCHAR(30) NOT NULL,
  placement VARCHAR(30) NOT NULL DEFAULT 'BEFORE_FLOORS',
  anchor_floor_id BIGINT UNSIGNED NULL,
  target_scope VARCHAR(10) NOT NULL DEFAULT 'ALL',
  sort_order INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  starts_at DATETIME NULL,
  ends_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id), KEY idx_ad_group_visible (status,placement,sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE home_ad_item (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  group_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(120) NULL,
  web_image_url VARCHAR(1000) NOT NULL,
  h5_image_url VARCHAR(1000) NULL,
  link_url VARCHAR(1000) NULL,
  open_target VARCHAR(10) NOT NULL DEFAULT 'SELF',
  sort_order INT NOT NULL DEFAULT 0,
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  PRIMARY KEY (id), KEY idx_ad_item_group (group_id,status,sort_order),
  CONSTRAINT fk_ad_item_group FOREIGN KEY (group_id) REFERENCES home_ad_group(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
