"use client";

import { useState } from "react";
import { addDemoRecord, deleteDemoRecord, saveDemoRecord, useBrowserRecords } from "../lib/browserDb";

type Tab = "home" | "category" | "solution" | "cart" | "mine";

const quickProducts = [
  { name: "得力 A4复印纸", spec: "70g · 8包/箱", price: "¥186", old: "¥229", tone: "paper", mark: "纸" },
  { name: "晨光中性笔", spec: "0.5mm · 12支/盒", price: "¥15.80", old: "¥22", tone: "pen", mark: "笔" },
  { name: "公牛插线板", spec: "6位 · 3米线", price: "¥42", old: "¥56", tone: "power", mark: "电" },
];

export default function H5Page() {
  const { records } = useBrowserRecords("商品管理");
  const { records: categoryRecords } = useBrowserRecords("商品分类");
  const mobileProducts = [...records.map((record,index)=>({name:record.name,spec:record.description||"后台新建自营商品",price:`¥${(record.price||0).toLocaleString("zh-CN")}`,old:`¥${Math.round((record.price||0)*1.15).toLocaleString("zh-CN")}`,tone:["paper","pen","power"][index%3],mark:"新"})),...quickProducts];
  const [tab, setTab] = useState<Tab>("home");
  const [cart, setCart] = useState(3);
  const [toast, setToast] = useState("");
  const [detail,setDetail]=useState<(typeof quickProducts)[number]|null>(null);
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 1800); };
  const add = () => { setCart((value) => value + 1); notify("已加入采购车"); };

  return <main className="h5Stage">
    <div className="h5Backdrop"><span>政企采购 · H5</span><h1>移动采购，随时随地</h1><p>协议价格、快速补货、订单物流与企业账户的移动端体验。</p><div><a href="../web/">Web 客户端</a><a href="../admin/">管理后台</a></div></div>
    <section className="phone">
      <div className="phoneStatus"><span>14:32</span><div>● ◒ ▰</div></div>
      <div className="phoneScreen">
        {detail?<H5ProductDetail product={detail} back={()=>setDetail(null)} add={add}/>:<>{tab === "home" && <H5Home add={add} items={mobileProducts} open={setDetail} />}
        {tab === "category" && <H5Category add={add} categories={[...categoryRecords.map(item=>item.name),"办公设备","办公耗材","网络设备","会议设备"]} />}
        {tab === "solution" && <H5Solution notify={notify} />}
        {tab === "cart" && <H5Cart count={cart} notify={notify} items={mobileProducts} />}
        {tab === "mine" && <H5Mine notify={notify} />}</>}
      </div>
      <nav className="h5Tabs">{[["home","⌂","首页"],["category","▦","分类"],["solution","◇","方案"],["cart","▱","采购车"],["mine","○","我的"]].map(([id, icon, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id as Tab)}><i>{icon}{id === "cart" && <b>{cart}</b>}</i><span>{label}</span></button>)}</nav>
      <div className="phoneHomeBar" />
      {toast && <div className="h5Toast">{toast}</div>}
    </section>
  </main>;
}

function H5Home({ add,items,open }: { add: () => void; items:typeof quickProducts;open:(product:typeof quickProducts[number])=>void }) {
  return <div className="h5Page"><header className="h5Header"><div><span className="h5Logo">政</span><div><strong>政企采购</strong><small>山东高速数字科技 · 协议已生效</small></div></div><button>♢<i /></button></header><label className="h5Search"><span>⌕</span><input placeholder="搜索商品、品牌、型号..." /><button>搜索</button></label><section className="h5Hero"><span>2026 政企集采季</span><h2>办公采购<br />一站配齐</h2><p>协议专属价格 · 自营正品保障</p><button>立即选购　›</button><b className="h5HeroGoods">💻　🖨️</b></section><div className="h5Shortcuts h5ShopNav">{[["纸","办公耗材"],["文","办公用品"],["电","电脑配件"],["国","国网专区"],["军","军网专区"],["青","青慧采"],["案","定制方案"],["全","全部分类"]].map((item,index) => <button key={item[1]}><i className={`navTone${index}`}>{item[0]}</i><span>{item[1]}</span></button>)}</div><section className="h5Section"><div className="h5SectionHead"><div><span>AGREEMENT PICKS</span><h3>协议精选</h3></div><button>全部 ›</button></div><div className="h5ProductScroll">{items.map((product) => <H5Product key={product.name} product={product} add={add} open={open} />)}</div></section><section className="h5Section"><div className="h5SectionHead"><div><span>SCENE SOLUTION</span><h3>方案推荐</h3></div><button>全部 ›</button></div><div className="h5SolutionStrip"><article><span>智慧办公</span><strong>整体解决方案</strong><small>办公设备 · 网络部署</small></article><article><span>智能会议</span><strong>会议室改造</strong><small>显示 · 音视频系统</small></article></div></section><section className="h5Order"><div className="h5SectionHead"><div><span>HOT PRODUCTS</span><h3>热门商品</h3></div><button>换一批</button></div><div className="h5ProductScroll">{items.slice().reverse().map((product) => <H5Product key={product.name} product={product} add={add} open={open} />)}</div></section></div>;
}

function H5Product({ product, add,open }: { product: typeof quickProducts[number]; add: () => void;open:(product:typeof quickProducts[number])=>void }) { return <article className="h5Product" onClick={()=>open(product)}><div className={`h5ProductImage ${product.tone}`}><span>协议价</span><b>{product.mark}</b></div><h4>{product.name}</h4><p>{product.spec}</p><div><strong>{product.price}</strong><del>{product.old}</del><button onClick={event=>{event.stopPropagation();add();}}>＋</button></div></article>; }

function H5ProductDetail({product,back,add}:{product:typeof quickProducts[number];back:()=>void;add:()=>void}){return <div className="h5Page h5Detail"><div className="h5SubHeader"><button onClick={back}>‹</button><h2>商品详情</h2><button>分享</button></div><div className={`h5DetailImage ${product.tone}`}><b>{product.mark}</b><span>1 / 4</span></div><article className="h5DetailInfo"><strong>{product.price}</strong><del>{product.old}</del><h1>{product.name}</h1><p>{product.spec}</p><div><span>自营正品</span><span>协议专价</span><span>全国配送</span></div></article><article className="h5DetailRow"><strong>配送</strong><span>现货 · 预计明日送达　›</span></article><article className="h5DetailRow"><strong>参数</strong><span>查看商品属性与规格　›</span></article><article className="h5DetailBody"><h3>商品详情</h3><p>政企采购自营商品，支持协议价格、多地址配送和统一对账。</p></article><footer className="h5DetailBuy"><button>客服</button><button onClick={add}>加入采购车</button><button onClick={add}>立即采购</button></footer></div>}

function H5Category({ add,categories }: { add: () => void;categories:string[] }) { const unique=categories.filter((item,index,array)=>array.indexOf(item)===index);const [selected,setSelected]=useState(unique[0]||"办公设备");return <div className="h5Page"><div className="h5SubHeader"><h2>商品分类</h2><button>⌕</button></div><div className="categoryLayout"><aside>{unique.map(item=><button className={selected===item?"active":""} onClick={()=>setSelected(item)} key={item}>{item}</button>)}</aside><section><div className="categoryBanner"><span>{selected}</span><b>企业焕新季</b></div><h3>三级分类</h3><div className="categoryTiles">{["笔记本","打印机","显示器","台式机","扫描仪","投影仪"].map((item,index)=><button key={item}><i>{["本","印","显","台","扫","投"][index]}</i><span>{item}</span></button>)}</div><h3>协议推荐</h3><div className="categoryRecommend"><span className="miniDevice">NB</span><div><strong>ThinkBook 16+</strong><small>协议价 ¥6,480</small></div><button onClick={add}>＋</button></div></section></div></div>; }

function H5Solution({ notify }: { notify: (message:string)=>void }) { const [selected,setSelected]=useState<string|null>(null);if(selected)return <div className="h5Page h5Detail"><div className="h5SubHeader"><button onClick={()=>setSelected(null)}>‹</button><h2>方案详情</h2><button>分享</button></div><div className="h5SolutionDetail"><span>SCENE SOLUTION</span><h1>{selected}整体解决方案</h1><p>设备选型、协议采购、配送安装与验收归档一站完成。</p><strong>方案价 ¥48,600</strong><button onClick={()=>notify("整套方案已加入采购车")}>整套加入采购车</button></div>{["需求与交付说明","方案商品清单（12件）","安装与售后服务"].map((item,index)=><article className="h5DetailSection" key={item}><b>0{index+1}</b><strong>{item}</strong><span>点击查看详细内容 ›</span></article>)}</div>;return <div className="h5Page"><div className="h5SubHeader"><h2>场景方案</h2><button>筛选</button></div><div className="solutionHero"><span>SMART OFFICE</span><h2>智慧会议室<br />一站式升级</h2><p>显示、音视频与协作设备组合</p><strong>方案价 ¥72,450</strong></div><div className="solutionList">{[["智慧办公","12件商品","¥48,600","蓝"],["园区安防","8件商品","¥36,800","橙"],["数据中心","16件商品","¥126,000","紫"]].map(item=><article key={item[0]} onClick={()=>setSelected(item[0])}><i className={item[3]}>{item[0].slice(0,1)}</i><div><strong>{item[0]}整体解决方案</strong><span>{item[1]} · 含安装服务</span><b>{item[2]}</b></div><button>›</button></article>)}</div></div>; }

function H5Cart({ count, notify, items }: { count:number; notify:(message:string)=>void; items:typeof quickProducts }) { const [checkout,setCheckout]=useState(false);const [submitted,setSubmitted]=useState(false);const submit=async()=>{await addDemoRecord({module:"订单管理",name:"H5企业采购订单",status:"待付款",description:"多地址配送 · 银行转账"});setSubmitted(true);notify("订单提交成功");};if(checkout)return <div className="h5Page h5CheckoutPage"><div className="h5SubHeader"><button onClick={()=>setCheckout(false)}>‹</button><h2>确认订单</h2><span/></div>{submitted?<div className="h5Success"><i>✓</i><h2>订单提交成功</h2><p>请根据转账说明完成线下银行转账</p><button onClick={()=>setCheckout(false)}>查看订单</button></div>:<><section><h3>收货地址与数量</h3>{["济南总部 · 2件","青岛项目部 · 1件","烟台办事处 · 1件"].map((item,index)=><label key={item}><input type="checkbox" defaultChecked/><span><strong>{item}</strong><small>{["经十路10001号","香港中路88号","迎春大街66号"][index]}</small></span></label>)}</section><section><h3>发票信息</h3><button>增值税专用发票　›</button></section><section><h3>付款方式</h3><p>线下银行转账 · 到账后安排发货</p></section><footer><div><small>应付</small><strong>¥6,723.80</strong></div><button onClick={()=>void submit()}>提交订单</button></footer></>}</div>;return <div className="h5Page cartPage"><div className="h5SubHeader"><h2>采购车</h2><button>管理</button></div><div className="cartAgreement"><i>✓</i><span>当前商品均已匹配企业协议最优价</span></div>{items.map((product,index)=><div className="h5CartItem" key={product.name}><button className="check">✓</button><div className={`cartThumb ${product.tone}`}>{product.mark}</div><div><strong>{product.name}</strong><span>{product.spec}</span><b>{product.price}</b><small>−　{index+1}　＋</small></div></div>)}<div className="h5Checkout"><div><span>合计</span><strong>¥6,723.80</strong><small>已节省 ¥1,024</small></div><button onClick={()=>setCheckout(true)}>结算 ({count})</button></div></div>; }

function H5Mine({notify}:{notify:(message:string)=>void}) { const [view,setView]=useState<"home"|"地址管理"|"发票管理"|"企业成员">("home");const module=`客户端:${view}`;const {records}=useBrowserRecords(module);const add=async()=>{await addDemoRecord({module,name:view==="地址管理"?"新增收货地址":"新增企业成员",description:"通过H5添加",status:"启用"});notify(`${view}已添加`);};if(view!=="home"){const seeds=view==="地址管理"?[["济南总部","经十路10001号 · 张经理"],["青岛项目部","香港中路88号 · 李主任"]]:view==="发票管理"?[["INV-202607-0082","专用发票 · ¥28,680 · 已开具"],["INV-202607-0079","普通发票 · ¥12,860 · 已开具"]]:[["张经理","企业管理员 · 启用"],["李采购","采购员 · 启用"]];return <div className="h5Page h5Manage"><div className="h5SubHeader"><button onClick={()=>setView("home")}>‹</button><h2>{view}</h2>{view!=="发票管理"?<button onClick={()=>void add()}>添加</button>:<span/>}</div>{[...records.map(item=>[item.name,item.description||""]),...seeds].map((item,index)=><article key={`${item[0]}-${index}`}><div><strong>{item[0]}</strong><span>{item[1]}</span></div>{view!=="发票管理"&&<div><button onClick={()=>{const value=window.prompt("请输入修改后的名称",item[0]);if(value&&records[index])void saveDemoRecord({...records[index],name:value});else if(value)void addDemoRecord({module,name:value,description:item[1],status:"启用"});}}>编辑</button>{records[index]&&<button onClick={()=>void deleteDemoRecord(records[index])}>删除</button>}{view==="企业成员"&&records[index]&&<button onClick={()=>void saveDemoRecord({...records[index],status:records[index].status==="启用"?"停用":"启用"})}>切换状态</button>}</div>}</article>)}</div>}return <div className="h5Page minePage"><div className="mineHero"><div className="mineAvatar">鲁</div><div><strong>山东高速数字科技</strong><span>张经理 · 企业主账号</span></div><button>›</button><section><div><span>本月采购</span><b>¥186,420</b></div><div><span>协议节省</span><b>¥28,640</b></div></section></div><div className="mineOrder"><div><strong>我的订单</strong><button>全部订单 ›</button></div><section>{[["付","待付款","1"],["货","待发货","0"],["运","运输中","2"],["完","已完成","36"]].map(item=><button key={item[1]}><i>{item[0]}</i><span>{item[1]}</span><b>{item[2]}</b></button>)}</section></div><div className="mineMenu">{[["址","地址管理"],["票","发票管理"],["员","企业成员"]].map(item=><button key={item[1]} onClick={()=>setView(item[1] as typeof view)}><i>{item[0]}</i><span>{item[1]}</span><em>›</em></button>)}</div><div className="agreementMini"><span><i />协议生效中</span><strong>2026年度采购框架协议</strong><small>有效期至2027年6月30日</small></div></div>; }
